# Generated by Django 4.0.4 on 2022-05-09 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0002_rename_chapters_chapter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'title')},
        ),
    ]
